FROM node:16-alpine

WORKDIR /usr/src/app

ARG DATABASE_URL=""
ENV DATABASE_URL $DATABASE_URL

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

RUN npx prisma generate

EXPOSE 3333

CMD ["npm", "run", "start:prod"]